'use client';
import {useEffect,useRef,useState} from 'react';
import {days} from './trip-data';
type Place={name:string;lat:number;lng:number;note:string;source:string;area?:boolean};
const places:Record<string,Place>={
station:{name:'银川站',lat:38.49168,lng:106.16862,note:'车站中心点；打车时确认进站口',source:'https://mapcarta.com/N9118892109'},
base:{name:'人民广场住宿区域',lat:38.485,lng:106.226,note:'建议住宿范围，非已预订酒店',source:'https://uri.amap.com/search?keyword=银川人民广场&city=银川&callnative=0',area:true},
museum:{name:'宁夏博物馆',lat:38.48446,lng:106.23073,note:'建筑中心点 · 人民广场东街',source:'https://mapcarta.com/W334447456'},
lanshan:{name:'览山公园',lat:38.52976,lng:106.21024,note:'公园中心点，非停车场入口',source:'https://mapcarta.com/W702598597'},
tombs:{name:'西夏陵',lat:38.435,lng:105.98722,note:'遗址参考点，非游客中心或售票入口',source:'https://zh.wikipedia.org/wiki/西夏陵'},
rock:{name:'贺兰山岩画遗址公园',lat:38.74707,lng:106.01435,note:'遗址公园中心点，非接驳入口',source:'https://mapcarta.com/W687881233'},
oldtown:{name:'兴庆老城活动范围',lat:38.465,lng:106.28,note:'仅示意老城片区；市场、小巷和店铺请用下方搜索核实',source:'https://uri.amap.com/search?keyword=银川鼓楼&city=银川&callnative=0',area:true},
art:{name:'银川当代美术馆（待复核）',lat:38.3666875,lng:106.368078125,note:'由原文位置码 8PC89989+M6W 解码，需以场馆地址复核',source:'https://uri.amap.com/search?keyword=银川当代美术馆&city=银川&callnative=0',area:true}
};
declare global{interface Window{L:any;__leafletReady?:Promise<any>}}
function getLeaflet(){if(window.L)return Promise.resolve(window.L);if(!window.__leafletReady)window.__leafletReady=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='/vendor/leaflet.js';const timeout=setTimeout(()=>reject(Error('timeout')),12000);s.onload=()=>{clearTimeout(timeout);resolve(window.L)};s.onerror=()=>{clearTimeout(timeout);reject(Error('load'))};document.head.appendChild(s)});return window.__leafletReady;}
export default function TripMap({day}:{day:number}){const ref=useRef<HTMLDivElement>(null);const map=useRef<any>(null);const [all,setAll]=useState(false);const [status,setStatus]=useState('正在载入地图…');const [selected,setSelected]=useState<Place|null>(null);const [retry,setRetry]=useState(0);const keys=all?Object.keys(places):days[day-1].places;const shown=keys.map(k=>places[k]).filter(Boolean);
useEffect(()=>{let alive=true;let instance:any;setStatus('正在载入地图…');setSelected(null);getLeaflet().then(L=>{if(!alive||!ref.current)return;instance=L.map(ref.current,{scrollWheelZoom:false,attributionControl:true});map.current=instance;const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors'}).addTo(instance);let errors=0;tiles.on('tileerror',()=>{errors++;if(alive&&errors>2)setStatus('底图暂时不可用，可通过地点搜索查看')});tiles.on('load',()=>{if(alive&&!errors)setStatus('在线底图 · 可拖动缩放')});const pts=shown.map(p=>[p.lat,p.lng]);shown.forEach((p,i)=>{if(p.area)L.circle([p.lat,p.lng],{radius:p.name.includes('美术馆')?250:850,color:'#8b9779',weight:1,dashArray:'4 4',fillOpacity:.12}).addTo(instance);const icon=L.divIcon({className:'trip-pin',html:'<span>'+(i+1)+'</span>',iconSize:[29,29],iconAnchor:[14,14]});const marker=L.marker([p.lat,p.lng],{icon,title:p.name,keyboard:true}).addTo(instance);const label=document.createElement('div');label.textContent=p.name;marker.bindTooltip(label,{direction:'top',offset:[0,-15]}).on('click',()=>setSelected(p));});if(pts.length>1&&!all)L.polyline(pts,{color:'#657951',weight:2,dashArray:'6 8',opacity:.7,interactive:false}).addTo(instance);if(pts.length)instance.fitBounds(L.latLngBounds(pts),{padding:[45,45],maxZoom:13});else instance.setView([38.48,106.25],11);L.control.scale({imperial:false}).addTo(instance);}).catch(()=>{if(alive)setStatus('地图加载失败，请重试或打开地点搜索')});return()=>{alive=false;instance?.remove();map.current=null}},[day,all,retry]);
return <><div className="map-actions"><span role="status">{status}</span><button onClick={()=>setAll(!all)}>{all?'只看当天':'查看全程'} ↗</button></div><div className="map" ref={ref} aria-label={'第'+day+'天地点交互地图'}/>{status.includes('失败')&&<button className="map-retry" onClick={()=>{window.__leafletReady=undefined;setRetry(retry+1)}}>重新加载地图</button>}<p className="map-caption">虚线仅为地点连线，非驾车路线或实时路况；圆圈表示参考范围。</p><div className="map-places">{shown.map((p,i)=><button key={p.name} className={selected?.name===p.name?'selected':''} onClick={()=>{setSelected(p);map.current?.flyTo([p.lat,p.lng],14,{duration:.6})}}><b>{i+1}</b>{p.name}</button>)}</div>{selected&&<div className="place-detail"><strong>{selected.name}</strong><p>{selected.note}</p><p>{selected.lat.toFixed(5)}° N, {selected.lng.toFixed(5)}° E · WGS84</p><a href={selected.source} target="_blank" rel="noreferrer">查看位置来源 ↗</a><a href={'https://uri.amap.com/search?keyword='+encodeURIComponent('银川 '+selected.name.replace('（待复核）',''))+'&city=银川&callnative=0'} target="_blank" rel="noreferrer">高德搜索 / 导航 ↗</a></div>}<p className="fine">地图点位用于地理参考，出发前通过高德按名称确认入口。店铺、音乐旧址及演出未设精确点位。</p></>}
