'use client';
import {useState} from 'react';
import {Mountain,MapPin,ArrowUpRight,ArrowRight,CalendarDays,Users,BedDouble,Clock3,Coffee} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {combinedDays} from '../combined-data';
import TripMap from '../trip-map';

const trains=[
  {title:'10 / 01 去太原',route:'成都东 → 太原南',code:'G3140',time:'16:02 → 22:36',price:'二等座待出票确认',alt:'约6小时34分。到站后直接入住太原站—柳巷一带，第二天开始完整游览。'},
  {title:'10 / 04 夜车',route:'太原 → 银川',code:'D267',time:'00:27 → 07:00',price:'卧铺参考 ¥191–283 / 人',alt:'10/3晚约23:40到太原站。车程约6小时33分，符合夜车不超过10小时的限制。'},
  {title:'10 / 07 返程',route:'银川 → 成都东',code:'D1709',time:'09:08 → 16:49',price:'参考 ¥587 / 人',alt:'备选D1957 08:11–15:54。优先同时候补，以出票结果为准。'}
];

export default function TaiyuanYinchuan(){
  const [day,setDay]=useState(1);
  return <><header className="topbar"><a href="#" className="brand"><Mountain/>行间 <small>TRAVEL NOTES</small></a><nav><a href="#itinerary">每日行程</a><a href="#prepare">出发准备</a><a href="#budget">旅行预算</a></nav><span className="edition">晋宁 · 2026 秋</span></header><main>
    <section className="intro"><div><p className="eyebrow">TAIYUAN → YINCHUAN / 01—07 OCTOBER</p><h1>两座城，七天。</h1><p className="intro-copy">十月一日从成都出发，<br/>把两个完整白天留给太原，再乘夜车去贺兰山下。</p><div className="meta"><span><CalendarDays/>10.01 — 10.07</span><span><Users/>2 人同行</span><span><BedDouble/>太原 2 晚 · 银川 3 晚 · 夜车 1 晚</span></div></div><figure><img src="/yinchuan.png" alt="贺兰山的山脉与山谷景观"/><figcaption>贺兰山 / 双城行程后半程</figcaption></figure></section>
    <div className="trip-rule"><span>成都东 <ArrowRight/> 太原 <ArrowRight/> 银川 <ArrowRight/> 成都东</span><span>10月1日出发 · 太原 2 个完整游览日 · 银川 3 个游览日</span></div>
    <section id="itinerary"><div className="heading"><div><p className="eyebrow">THE BALANCED ITINERARY</p><h2>两城之间，更均衡一点</h2></div><span className="muted">选择日期，查看当天安排与地点</span></div><Tabs value={day} onValueChange={v=>setDay(Number(v))}><TabsList className="day-tabs">{combinedDays.map((d,i)=><TabsTrigger key={i} value={i+1} className="day-tab"><span>DAY 0{i+1}<small>10 / 0{i+1}</small></span>{d.short}</TabsTrigger>)}</TabsList>{combinedDays.map((d,i)=><TabsContent key={i} value={i+1}><div className="day-layout"><article><div className="daily-title"><span className="large-number">0{i+1}</span><div><p className="eyebrow">10月{i+1}日 · {d.city} · {d.week}</p><h3>{d.title}</h3></div></div><div className="tags"><span><Clock3/>{d.transit}</span><span>{d.energy}</span></div><p className="day-note">{d.note}</p><ol className="timeline">{d.events.map((e,j)=>{const city=d.city==='太原'?'太原':'银川';return <li key={j}><time>{e[0]}</time><div><h4>{e[1]}</h4><p>{e[2]}</p>{e[3]&&<a className="place-link" href={'https://uri.amap.com/search?keyword='+encodeURIComponent(city+' '+e[3])+'&city='+city+'&callnative=0'} target="_blank" rel="noreferrer"><MapPin/>{e[3]}<ArrowUpRight/></a>}</div></li>})}</ol><div className="tip"><Coffee/><p>{d.tip}</p></div></article><aside className="map-column"><div className="map-heading"><span><MapPin/> 当天地理位置</span><span className="live-dot">OpenStreetMap</span></div><TripMap day={i+1} itinerary={combinedDays}/><div className="route-summary"><p className="eyebrow">TODAY'S RHYTHM</p><h4>{d.rhythm}</h4><p>{d.route}</p></div></aside></div></TabsContent>)}</Tabs></section>
    <section id="prepare"><div className="heading"><div><p className="eyebrow">BEFORE YOU GO</p><h2>三段车票，两个住宿点</h2></div><a className="text-link" href="https://www.12306.cn/" target="_blank" rel="noreferrer">打开 12306 <ArrowUpRight/></a></div><div className="prepare-grid"><article><h3>抢票与预约节点</h3>{[['现在—9/16','订太原2晚、银川3晚可免费取消酒店'],['9/17','抢10/1成都东→太原南 G3140'],['9/20','抢10/4凌晨太原→银川 D267'],['9/23','抢10/7银川→成都东返程'],['9/27—9/29','预约晋祠、山西博物院、宁夏博物馆'],['9/30','核对天气、国庆开放与夜车车站']].map(([date,text])=><div className="booking-row" key={date}><time>{date}</time><p>{text}</p></div>)}<p className="fine">抢票日按15天预售期（含乘车日）推算；起售时刻、车次与是否开行，以12306最终页面为准。</p></article><article className="hotel"><BedDouble/><p className="eyebrow">TWO BASES, FIVE HOTEL NIGHTS</p><h3>太原站—柳巷 / 银川人民广场</h3><p>10/1—10/3太原住两晚，方便老城并兼顾10/3深夜前往太原站；10/4—10/7银川住三晚，仍以人民广场—北京中路为据点。</p><div className="hotel-price">¥1,750–2,250 <span>/ 两地住宿目标总价</span></div><a className="text-link" href="https://uri.amap.com/search?keyword=太原柳巷酒店&city=太原&callnative=0" target="_blank" rel="noreferrer">查看太原住宿区 <ArrowUpRight/></a><p className="fine">10/3白天退房后寄存行李；若酒店无法提供晚间洗漱，可预订钟点房或选择带休息室的车站服务。</p></article></div><div className="train-grid three-trains">{trains.map(t=><article className="train" key={t.code}><p className="eyebrow">{t.title}</p><h3>{t.route}<small>{t.code}</small></h3><div className="train-time">{t.time}<span>{t.price}</span></div><p>{t.alt}</p></article>)}</div><p className="fine">当前为规划参考，不是实时票务结果。特别注意D267由“太原站”出发，G3140抵达“太原南站”。</p></section>
    <section id="budget" className="budget"><div><p className="eyebrow">TRAVEL BUDGET / FOR TWO</p><h2>多一座城，仍留有余量。</h2><p className="budget-total">¥8,800–10,200</p><p className="muted">两人目标预算 · 含三段城际交通与五晚酒店</p><p className="fine">夜车替代一晚酒店，但卧铺价格与国庆房价波动较大，建议另留约¥800机动预算。</p></div><div className="budget-items">{[['三段城际列车','¥2,500–3,100'],['五晚住宿','¥1,750–2,250'],['两城市内与郊区交通','¥700–1,000'],['晋祠、西夏陵、岩画等','¥500–750'],['餐饮','¥2,000–2,600'],['演出、酒饮与伴手礼','¥500–900']].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div></section>
    <footer><span><Mountain/> 太原 · 银川双城七日</span><p>10月1日出发：太原2个完整游览日，银川3个游览日。<br/>开放、票价、交通与演出以出行前官方公告为准。</p><a href="#">回到顶部 ↑</a></footer>
  </main></>;
}
